### ISSUE TITLE
OpenGraph tags

### ISSUE THREAD

**Issue by jamierytlewski** [lansingcodes/www#87]
Why does the OpenGraph tag have an SVG for the image? I know SVG images are "cleaner", but many sites (Twitter, MS Teams, iMessage) do not support SVG's for the images.

**Comment by egillespie** [comment]
Hi @jamierytlewski, sorry for taking a while to respond. I was buried in student code reviews in April and missed the notification of your issue.

You make a great point and I wanted to let you know that a new version of the website was launched this morning. The OpenGraph image tag now points at a binary image instead of an SVG. I plan to make a better and optimized version of the image down the road, but at least moving forward more sites will be able to unfurl the website.

Thanks for the recommendation! 👍

**Comment by jamierytlewski** [comment]
Erik,

Thanks for the reply. I had actually forgot about the issue. Thanks for
following up. Good luck. Jamie
